version: '3'

services:
    db:
        image: postgres:12.0-alpine
        expose:
            - 5432
        ports:
            - "5432:5432"
        volumes:
            - ./var/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: acnh